use_frameworks!

platform :ios, '8.0'

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'XJHNetworkInterceptorKit_Example' do
  pod 'XJHNetworkInterceptorKit', :path => '../'
  target 'XJHNetworkInterceptorKit_Tests' do
    inherit! :search_paths

    
  end
end
